INSERT INTO PRODUCT_ORDER (ID, DESCRIPTION, COST)
VALUES (1001, 'Carpet', '£12.34');
INSERT INTO PRODUCT_ORDER (ID, DESCRIPTION, COST)
VALUES (1002, 'Sofa', '£9.30');
INSERT INTO PRODUCT_ORDER (ID, DESCRIPTION, COST)
VALUES (1003, 'Cooking Gloves', '£8.00');
