INSERT INTO TODO (ID, DESCRIPTION, COMPLETED)
VALUES (2001, 'Select products', TRUE);
INSERT INTO TODO (ID, DESCRIPTION, COMPLETED)
VALUES (2002, 'Bill at the counter', FALSE);
INSERT INTO TODO (ID, DESCRIPTION, COMPLETED)
VALUES (2003, 'Provide feedback', FALSE);
